require.config({
	baseUrl:'/',
	paths:{
		'angular':'./lib/angular/angular.min',
		'asyncLoader':'./lib/angular-async-loader/angular-async-loader.min',
		'angularUiRouter':'./lib/angular-ui-router/angular-ui-router.min',
		'app':'app'
	},
	shim:{
		'app':{deps:['angular','angularUiRouter']},
		'angular':{exports:'angular'},
		'asyncLoader':{deps:['angular'],exports:'asyncLoader'},
		'angularUiRouter':{deps:['angular']},
	}
});

require(['app-routes'],function(appRoutes){
	angular.element(document).ready(function(){
		angular.bootstrap(document,['directiveDemo']);
	})
})